build:
  image: continuumio/miniconda3:latest
  stage: build
  before_script:
    - apt-get update
    - apt-get -y install iverilog
    - apt-get -y install yosys
    - conda env create -f environment.yml
    - source activate myhdl
  script:
    - cd ./verif/
    - python testbench.py
    - cd ../verif_rtl/
    - python testbench_cosim.py
    ##- iverilog -o localization -c ../../rtl/filelist.f -g 2005
    ##- vvp localization
    ##- cd ../../syn/
    ##- yosys -s yosys_script